### ISSUE TITLE
Funcition 'has' when using matlab for gradients

### ISSUE THREAD

**Issue by brunoml5** [torrisig/FalcOpt#1]
Hello everyone,

I'm having some problems to run the example with the option 'matlab' for gradients. It says that the function 'has' from the symbolic toolbox in falcopt.fcn2struct (line 67) does not exist. 

From their website (https://www.mathworks.com/help/symbolic/has.html) I saw that it was introduced in R2015b. Maybe this line could be written differently so that the code could be used on different Matlab versions.

My Matlab version is R2015a and Symbolic Math Toolbox is v6.2.

Kind Regards,
Bruno

**Comment by torrisig** [comment]
Hi Bruno,

this will be fixed in a new version appearing in a couple of days.

Thanks,
Giampaolo

**Comment by tommasro** [comment]
Hi Bruno,

the function `has` has now been substitute. The new version should work with your Matlab version too.

Regards,
Tommaso
