### ISSUE TITLE
Line-search failed with weird tolerance values

### ISSUE THREAD

**Issue by roversch** [torrisig/FalcOpt#10]
Every second time I run FalcOpt, I get the following Warning in MATLAB: 

    Warning: Line-search failed to progress. Close to solution, may not be a problem:
        optimality tolerance 4017166141827934, feasibility tolerance -100. Continuing...  

These seem to be an invalid value for the tolerances. I attached the script that I use to call FalcOpt.

[falcopt_run.txt](https://github.com/torrisig/FalcOpt/files/2034935/falcopt_run.txt)

When I restart my script, FalcOpt yields the correct results again.

**Comment by dafrick** [comment]
Interesting. I will take a look.
