### ISSUE TITLE
Folder name 'FalcOpt' on example

### ISSUE THREAD

**Issue by brunoml5** [torrisig/FalcOpt#2]
Hello everyone,

When clonning the repository, at least on SourceTree, the default name for the folder is 'FalcOpt', the same name of the export folder for the example (generateMotor.m, line 28, 'FalcOpt').

Running the example, there is a problem generateCode.m line 1529. The folloing code checks if the folder 'FalcOpt' exists and Matlab returns 7 (same as true).
`if exist(file_folder, 'dir')~=7`
        `mkdir(file_folder);`
  `  end`

Because of that, the next line (`cd (sprintf(o.gendir))` ) fails because there it can't find 'FalcOpt' on the current folder.

Changing the 'gendir' directory to another string, e.g. 'export', works.

My Matlab version is R2015a and the root folder 'FalcOpt' is added on the path along with its subfolders.

Kind Regards,
Bruno

**Comment by torrisig** [comment]
Dear Bruno,

it is sufficient to add the folder containing +falcopt **without subfolders** or, as you said, change the gendir name of the folder. We have updated the considered example.  

Thanks,
Giampaolo
