### ISSUE TITLE
Function 'split', Matlab version R2015a

### ISSUE THREAD

**Issue by brunoml5** [torrisig/FalcOpt#3]
Hi again,

I had a problem with the function split, num2str.m line 72 (`pieces = split(s, 'e');`):
`Undefined function 'split' for input arguments of type 'char'.`

At this point, s='-1' and I am not sure why this is happening.

Changing the function to 'strsplit' solves the problem for me. Maybe there could be an if else here to check the matlab version to use either 'split' or 'strsplit'.

Kind regards,
Bruno

**Comment by dafrick** [comment]
Thanks! Has been fixed to use only strsplit.
