### ISSUE TITLE
Problems with 'casadi' option for gradients

### ISSUE THREAD

**Issue by brunoml5** [torrisig/FalcOpt#4]
Hello everyone,

I'm had two problems with casadi functions because matlab could not find them. It happened two lines from generateCode.m:

- line 1723, `z = SX.sym('u',[o.nu,1]);`

- line 1891, `y_f{jj} = Function(['build_n_' num2str(jj) '_casadi'],{z},{in_n{jj}.stored.values});`

I am not sure what the problem is but I solved it adding the following code before each error:
`import casadi.*`

My Casadi version is 3.1.1 and all of its folders and subfolders are added to the path.

Kind regards,
Bruno

**Comment by torrisig** [comment]
Dear Bruno,

this seems to be a Casadi issue. Could you check if `import casadi.*` at line 1697 is executed please? This should suffice and no more import casadi.* would be needed. Could you also possibly try to include only casadi folder and not its subfolders?

Thanks,
Giampaolo

**Comment by brunoml5** [comment]
Hi,

I added only FalcOpt and Casadi folder now, no subfolders.

The code `strcmp(o.gradients,'casadi')` returns true at line 1697.

If I add the line `disp('blablabla')` below `import casadi.*` and put a breakpoint in `disp`, SX is available on the console (so it finds casadi, I guess). But if I continue the script, there is an error on line 1893 `y_f{jj} = Function(['build_n_' num2str(jj) '_casadi'],{z},{in_n{jj}.stored.values});`.

If I leave `disp` and put `import casadi.*` before line 1893, it works. It is a really strange bug.

Regards,
Bruno

**Comment by tommasro** [comment]
Hi Bruno,

with the new version the bug should have been fixed.  The problem was, according to Matlab documentation, that 

> Matlab preprocesses the `import` statement before evaluating the variables in the conditional statements


Please let us know if the problem persists.

Thanks,
Tommaso
