### ISSUE TITLE
Mex generation fails with the 'precision' set to 'single'

### ISSUE THREAD

**Issue by spinv** [torrisig/FalcOpt#5]
Great project, thanks for sharing the code. 

Everything works fine with the precision set to 'double' though appears to fail when 'single' is used. 

It seems that when setting "real  = 'single' " in the generateMotor example file, passes the tests in the "falcopt.generateCode", but then 'single' is still used internally in the code generation instead of 'float'. Thus, I get errors of the type:
FalcOpt-master\example\generatedCode\Motor_example_FalcOpt.c:673:43: error: unknown type name 'single'
 static void solveConstraintSystem_invert1(single* Mi, const single* M) {
                                                                      ^
It looks as if 'o.precision' and 'o.real' would be used interchangeably in the code-generation phase.

Regards,
VS

**Comment by dafrick** [comment]
Thanks VS, for finding this bug. Should be fixed in the most recent version. Let us know if more issues pop up.

Best,
Damian
