### ISSUE TITLE
Use generated C code in standalone application

### ISSUE THREAD

**Issue by brunoml5** [torrisig/FalcOpt#6]
Hi,

how can I run the generated C code outside Matlab? Is it only tailored for Matlab? Is it possible to embed it?

Kind Regards,
Bruno

**Comment by dafrick** [comment]
Hi Bruno,

Thanks for taking an interest in falcopt. It is indeed possible to embed the generated C code. In fact, one of the main goals of this tool was to generate embeddable code. 

If you call `falcopt.generateCode` with the additional option `'buildTypes', {'mex', 'production'}`, then both C code to generate a MEX file, as well as pure "production" C code (without MEX) will be generated. You can find the generated C code in the folder specified via the option `'gendir'`. There will a file called `'name'_mex.c` and one `'name'.c`, where `'name'` is the name you selected for your solver via the 'name' option. Depending on what you chose as your 'gradients' options, there may be some additional files. 

The file `'name'.c` contains the functions that you need to call in your embedded application (have a look at the function of `'name'_mex.c` to get an idea of how they are used). The function to solve the optimization problem is `proposed_algorithm()`, where the number of arguments depends on the `'debug'` option, i.e., it has fewer arguments when debug is lower. For optimal performance choose `'debug', 0`.
IMPORTANT: We do not allocate memory for you. So all the pointers you pass as arguments to `proposed_algorithm()` need to point to an allocated memory of proper size.

I hope this helps. Please let me know if there are any issues of further questions.

**Comment by torrisig** [comment]
Thanks!

Giampaolo
