### ISSUE TITLE
getAlgorithmSize is deprecated

### ISSUE THREAD

**Issue by roversch** [torrisig/FalcOpt#9]
I get following error message from FalcOpt: 

    No appropriate method, property, or field 'getAlgorithmSize' for class 'casadi.Function'. 

I checked, and this method does not exist anymore in CasADi. Could you either remove this or specify which version of CasADi I should use?

**Comment by dafrick** [comment]
Thanks for letting us know, Robin.

getAlgorithmSize() has been replaced with n_instructions() in version 3.3.0 of CasADi. I have updated FalcOpt, which should now work both for 3.3.0 and for earlier versions. Please let me know whether it works.

Best,
Damian

**Comment by roversch** [comment]
Thanks, that was fast! I have another one for you:

    No appropriate method, property, or field 'getWorkSize' for class 'casadi.Function'.

**Comment by dafrick** [comment]
Fixed (probably). Let me know whether it works.

**Comment by roversch** [comment]
Thx Damian. One more:

    .../casadi/core/code_generator.cpp:84: Unrecongnized option: real_t 

in `falcopt.generateCode>generate_casadi_c (line 1461)`, should be `casadi_real`.

**Comment by dafrick** [comment]
Thanks! Should now also be fixed in the latest commit.

**Comment by roversch** [comment]
Works! thanks
